version: '3.8'

services:
  web:
    build: .
    container_name: django_app  
    volumes:
      - static:/app/staticfiles
      - ./:/app  
    environment:
      SECRET_KEY: "super_secret"
      DEBUG: "False"
      DATABASE_URL: "postgresql://postgres:shit@5.129.207.182:5432/hr_eff"
      REDIS_URL: "redis://:belx001%22@hr_redis:6399/0"  # Добавлено подключение к Redis
      IS_URL: "True"
      RESET_PASSWORD_COMMAND: "hello"
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend_network  # Исправлена опечатка (было bacckend_network)
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
              python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createcachetable &&
            gunicorn --bind 0.0.0.0:8000 laborcount.wsgi:application"

  redis:
    image: redis:7.2-alpine
    container_name: hr_redis
    ports:
      - "6399:6399"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass belx001%22
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "belx001%22", "ping"]  # Добавлен пароль
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend_network

volumes:
  redis_data:
  static:

networks:
  backend_network:  # Единая сеть для всех сервисов
    driver: bridge